// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkabIX4PpAGaVQf7ni8AU7eUB78ngJiDk',
    appId: '1:32660558108:web:8eb30538b8cd916753ead9',
    messagingSenderId: '32660558108',
    projectId: 'aksabeg-b6571',
    authDomain: 'aksabeg-b6571.firebaseapp.com',
    databaseURL: 'https://aksabeg-b6571-default-rtdb.firebaseio.com',
    storageBucket: 'aksabeg-b6571.firebasestorage.app',
    measurementId: 'G-3CLR32M09N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCczxrmzYiFRZuDHOqhgqcH-DGvV1z8WZ0',
    appId: '1:32660558108:android:0646a3e54a8b1d9e53ead9',
    messagingSenderId: '32660558108',
    projectId: 'aksabeg-b6571',
    databaseURL: 'https://aksabeg-b6571-default-rtdb.firebaseio.com',
    storageBucket: 'aksabeg-b6571.firebasestorage.app',
  );
}
