// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1eholuDAnsQTI-fcTqVVM4A9o7a02FUU',
    appId: '1:549455573441:web:757e2dfa938c8267c4ff40', // تم إسقاطها توافقياً مع المشروع الجديد
    messagingSenderId: '549455573441',
    projectId: 'aksab-erp',
    authDomain: 'aksab-erp.firebaseapp.com',
    databaseURL: 'https://aksab-erp-default-rtdb.firebaseio.com',
    storageBucket: 'aksab-erp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1eholuDAnsQTI-fcTqVVM4A9o7a02FUU',
    appId: '1:549455573441:android:306272e4aa203672c4ff40',
    messagingSenderId: '549455573441',
    projectId: 'aksab-erp',
    databaseURL: 'https://aksab-erp-default-rtdb.firebaseio.com',
    storageBucket: 'aksab-erp.firebasestorage.app',
  );
}